const express = require('express')
express()
  .use(express.static(__dirname))
  .get('*', (req, res) => res.sendFile(__dirname + '/index.html'))
  .listen(3000, () => console.log('Listening at 3000'))
